resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: flight-school
  type: git
  source:
    uri: https://github.com/justice3120/flight-school
    branch: master
- name: notify-slack
  type: slack-notification
  source:
    url: https://hooks.slack.com/services/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
- name: hoge
  type: git
  source:
    uri: https://github.com/justice3120/flight-school
    branch: master

jobs:
- name: test-app
  plan:
  - get: flight-school
    trigger: true
  - get: hoge
  - task: tests
    file: flight-school/build.yml
  - put: notify-slack
    params:
      channel: "#swet-testinfra-notify"
      text: "Hello from concourse"
      username: "Consourse"
      icon_url: "https://blog.altoros.com/wp-content/uploads/2016/05/concourse-ci-7809479.png"
- name: job2
  plan:
  - get: hoge
    trigger: true
    passed: [test-app]
  - task: tests
    file: flight-school/build_local.yml
